# -*- encoding: utf-8 -*

# -*- encoding: utf-8 -*
Category.create!  :apphera_id  => 2,  :name => "Autoglas",  :country => "de"
print "."
Category.create!  :apphera_id  => 3,  :name => "Autohäuser",  :country => "de"
print "."
Category.create!  :apphera_id  => 4,  :name => "Autolackierer",  :country => "de"
print "."
Category.create!  :apphera_id  => 5,  :name => "Autoleasing",  :country => "de"
print "."
Category.create!  :apphera_id  => 6,  :name => "Autoschrotthandel",  :country => "de"
print "."
Category.create!  :apphera_id  => 7,  :name => "Autotuning",  :country => "de"
print "."
Category.create!  :apphera_id  => 9,  :name => "Fahrschulen",  :country => "de"
print "."
Category.create!  :apphera_id  => 10,  :name => "Fahrzeugbau",  :country => "de"
print "."
Category.create!  :apphera_id  => 11,  :name => "Flughafentransfer",  :country => "de"
print "."
Category.create!  :apphera_id  => 15,  :name => "Motorräder",  :country => "de"
print "."
Category.create!  :apphera_id  => 16,  :name => "Nutzfahrzeuge",  :country => "de"
print "."
Category.create!  :apphera_id  => 17,  :name => "Oldtimer",  :country => "de"
print "."
Category.create!  :apphera_id  => 18,  :name => "Parkhäuser",  :country => "de"
print "."
Category.create!  :apphera_id  => 19,  :name => "Reifendienste",  :country => "de"
print "."
Category.create!  :apphera_id  => 20,  :name => "Schrotthandel",  :country => "de"
print "."
Category.create!  :apphera_id  => 21,  :name => "Tankstellen",  :country => "de"
print "."
Category.create!  :apphera_id  => 22,  :name => "Vermietung",  :country => "de"
print "."
Category.create!  :apphera_id  => 23,  :name => "Waschanlagen",  :country => "de"
print "."
Category.create!  :apphera_id  => 24,  :name => "Werkstätten",  :country => "de"
print "."
Category.create!  :apphera_id  => 25,  :name => "Abbruchunternehmen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 26,  :name => "Bauhandwerk",  :country => "de"
print "."
Category.create!  :apphera_id  => 27,  :name => "Baumaschinen",  :country => "de"
print "."
Category.create!  :apphera_id  => 28,  :name => "Bauplanung",  :country => "de"
print "."
Category.create!  :apphera_id  => 29,  :name => "Baustoffe",  :country => "de"
print "."
Category.create!  :apphera_id  => 30,  :name => "Hallenbau ",  :country => "de"
print "."
Category.create!  :apphera_id  => 31,  :name => "Montagearbeiten ",  :country => "de"
print "."
Category.create!  :apphera_id  => 32,  :name => "Restaurierung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 33,  :name => "Sanierung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 34,  :name => "Stuckateure ",  :country => "de"
print "."
Category.create!  :apphera_id  => 35,  :name => "Abfallwirtschaft",  :country => "de"
print "."
Category.create!  :apphera_id  => 36,  :name => "Altenheime ",  :country => "de"
print "."
Category.create!  :apphera_id  => 37,  :name => "Altenpflege ",  :country => "de"
print "."
Category.create!  :apphera_id  => 38,  :name => "Bestattungen",  :country => "de"
print "."
Category.create!  :apphera_id  => 40,  :name => "Jugendeinrichtungen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 41,  :name => "Mediation ",  :country => "de"
print "."
Category.create!  :apphera_id  => 42,  :name => "Notdienste",  :country => "de"
print "."
Category.create!  :apphera_id  => 44,  :name => "Seniorenwohnungen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 46,  :name => "Sozialdienste",  :country => "de"
print "."
Category.create!  :apphera_id  => 47,  :name => "Stadtarchiv ",  :country => "de"
print "."
Category.create!  :apphera_id  => 48,  :name => "Stiftungen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 49,  :name => "Supervision ",  :country => "de"
print "."
Category.create!  :apphera_id  => 50,  :name => "Verbraucherzentralen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 51,  :name => "Wasser",  :country => "de"
print "."
Category.create!  :apphera_id  => 52,  :name => "Wohnungs- und Zimmervermittlung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 56,  :name => "Arbeitssicherheit ",  :country => "de"
print "."
Category.create!  :apphera_id  => 57,  :name => "Arbeitsvermittlung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 58,  :name => "Berufliche Weiterbildung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 59,  :name => "Berufsbildende Schulen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 60,  :name => "Berufsbildung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 61,  :name => "Berufsgenossenschaften",  :country => "de"
print "."
Category.create!  :apphera_id  => 62,  :name => "Bildungseinrichtungen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 63,  :name => "Computerschulung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 64,  :name => "Erwachsenenbildung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 66,  :name => "Fahrschulen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 67,  :name => "Flugschulen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 68,  :name => "Hochschulen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 69,  :name => "Nachhilfeunterricht ",  :country => "de"
print "."
Category.create!  :apphera_id  => 70,  :name => "Personalberatung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 71,  :name => "Privatschulen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 72,  :name => "Schulen",  :country => "de"
print "."
Category.create!  :apphera_id  => 73,  :name => "Schulverwaltungsamt ",  :country => "de"
print "."
Category.create!  :apphera_id  => 74,  :name => "Sportschulen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 75,  :name => "Sprachschulen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 76,  :name => "Zeitarbeit",  :country => "de"
print "."
Category.create!  :apphera_id  => 78,  :name => "Computer Service",  :country => "de"
print "."
Category.create!  :apphera_id  => 79,  :name => "EDV ",  :country => "de"
print "."
Category.create!  :apphera_id  => 80,  :name => "Internet ",  :country => "de"
print "."
Category.create!  :apphera_id  => 81,  :name => "Internet-Cafés ",  :country => "de"
print "."
Category.create!  :apphera_id  => 82,  :name => "Kommunikation und Netzwerke ",  :country => "de"
print "."
Category.create!  :apphera_id  => 83,  :name => "Software ",  :country => "de"
print "."
Category.create!  :apphera_id  => 84,  :name => "Web-Design ",  :country => "de"
print "."
Category.create!  :apphera_id  => 85,  :name => "Apotheken ",  :country => "de"
print "."
Category.create!  :apphera_id  => 86,  :name => "Blutspendedienste ",  :country => "de"
print "."
Category.create!  :apphera_id  => 88,  :name => "Heilpraktiker",  :country => "de"
print "."
Category.create!  :apphera_id  => 89,  :name => "Hilfsdienste ",  :country => "de"
print "."
Category.create!  :apphera_id  => 90,  :name => "Hörgeräte ",  :country => "de"
print "."
Category.create!  :apphera_id  => 91,  :name => "Krankenhäuser",  :country => "de"
print "."
Category.create!  :apphera_id  => 92,  :name => "Laborbedarf ",  :country => "de"
print "."
Category.create!  :apphera_id  => 93,  :name => "Labordiagnostik ",  :country => "de"
print "."
Category.create!  :apphera_id  => 95,  :name => "Medizinischer Fachbedarf ",  :country => "de"
print "."
Category.create!  :apphera_id  => 96,  :name => "Optiker",  :country => "de"
print "."
Category.create!  :apphera_id  => 98,  :name => "Osteopathie ",  :country => "de"
print "."
Category.create!  :apphera_id  => 99,  :name => "Pflegedienste",  :country => "de"
print "."
Category.create!  :apphera_id  => 100,  :name => "Physiotherapie",  :country => "de"
print "."
Category.create!  :apphera_id  => 101,  :name => "Psychiatrie und Psychotherapie",  :country => "de"
print "."
Category.create!  :apphera_id  => 102,  :name => "Reformhäuser ",  :country => "de"
print "."
Category.create!  :apphera_id  => 103,  :name => "Rehabilitation",  :country => "de"
print "."
Category.create!  :apphera_id  => 105,  :name => "Schwangerschaft und Geburt",  :country => "de"
print "."
Category.create!  :apphera_id  => 106,  :name => "Suchtberatung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 107,  :name => "Zahnmedizin",  :country => "de"
print "."
Category.create!  :apphera_id  => 108,  :name => "Ärzte",  :country => "de"
print "."
Category.create!  :apphera_id  => 109,  :name => "Bar",  :country => "de"
print "."
Category.create!  :apphera_id  => 111,  :name => "Cafés ",  :country => "de"
print "."
Category.create!  :apphera_id  => 112,  :name => "Catering",  :country => "de"
print "."
Category.create!  :apphera_id  => 113,  :name => "Eiscafés ",  :country => "de"
print "."
Category.create!  :apphera_id  => 114,  :name => "Feinkost ",  :country => "de"
print "."
Category.create!  :apphera_id  => 115,  :name => "Fleischereien ",  :country => "de"
print "."
Category.create!  :apphera_id  => 117,  :name => "Konditoreien ",  :country => "de"
print "."
Category.create!  :apphera_id  => 118,  :name => "Lebensmittel ",  :country => "de"
print "."
Category.create!  :apphera_id  => 119,  :name => "Lieferservices ",  :country => "de"
print "."
Category.create!  :apphera_id  => 120,  :name => "Meeresfrüchte ",  :country => "de"
print "."
Category.create!  :apphera_id  => 122,  :name => "Pubs / Kneipen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 123,  :name => "Restaurants",  :country => "de"
print "."
Category.create!  :apphera_id  => 124,  :name => "Süßwaren ",  :country => "de"
print "."
Category.create!  :apphera_id  => 125,  :name => "Tiefkühlkost ",  :country => "de"
print "."
Category.create!  :apphera_id  => 126,  :name => "Biergärten ",  :country => "de"
print "."
Category.create!  :apphera_id  => 127,  :name => "Bistro ",  :country => "de"
print "."
Category.create!  :apphera_id  => 128,  :name => "Erlebnisgastronomie ",  :country => "de"
print "."
Category.create!  :apphera_id  => 130,  :name => "Pizza ",  :country => "de"
print "."
Category.create!  :apphera_id  => 131,  :name => "Restaurant: Amerikanisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 132,  :name => "Restaurant: Arabisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 133,  :name => "Restaurant: Asiatisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 134,  :name => "Restaurant: Brasilianisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 135,  :name => "Restaurant: Chinesisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 136,  :name => "Restaurant: Deutsch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 137,  :name => "Restaurant: Fisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 141,  :name => "Restaurant: Griechisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 142,  :name => "Restaurant: Indisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 144,  :name => "Restaurant: Italienisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 145,  :name => "Restaurant: Japanisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 146,  :name => "Restaurant: Koreanisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 147,  :name => "Restaurant: Kroatisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 148,  :name => "Restaurant: Libanesisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 149,  :name => "Restaurant: Mediterran ",  :country => "de"
print "."
Category.create!  :apphera_id  => 150,  :name => "Restaurant: Mexikanisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 151,  :name => "Restaurant: Polnisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 152,  :name => "Restaurant: Portugiesisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 153,  :name => "Restaurant: Russisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 154,  :name => "Restaurant: Spanisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 155,  :name => "Restaurant: Steakhaus ",  :country => "de"
print "."
Category.create!  :apphera_id  => 156,  :name => "Restaurant: Thailändisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 157,  :name => "Restaurant: Tibetisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 158,  :name => "Doener Restaurant",  :country => "de"
print "."
Category.create!  :apphera_id  => 159,  :name => "Restaurant: Vegetarisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 160,  :name => "Restaurant: Vietnamesisch ",  :country => "de"
print "."
Category.create!  :apphera_id  => 161,  :name => "Restaurant: verschiedene ",  :country => "de"
print "."
Category.create!  :apphera_id  => 162,  :name => "Schnellrestaurants ",  :country => "de"
print "."
Category.create!  :apphera_id  => 163,  :name => "Anlageberatung",  :country => "de"
print "."
Category.create!  :apphera_id  => 164,  :name => "Banken",  :country => "de"
print "."
Category.create!  :apphera_id  => 165,  :name => "Beteiligungsgesellschaften ",  :country => "de"
print "."
Category.create!  :apphera_id  => 167,  :name => "Finanzbuchhaltung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 168,  :name => "Finanzierungsunternehmen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 169,  :name => "Immobilien",  :country => "de"
print "."
Category.create!  :apphera_id  => 170,  :name => "Kassensysteme ",  :country => "de"
print "."
Category.create!  :apphera_id  => 171,  :name => "Kundendienste ",  :country => "de"
print "."
Category.create!  :apphera_id  => 172,  :name => "Leasing ",  :country => "de"
print "."
Category.create!  :apphera_id  => 174,  :name => "Schulden",  :country => "de"
print "."
Category.create!  :apphera_id  => 175,  :name => "Steuerberater ",  :country => "de"
print "."
Category.create!  :apphera_id  => 176,  :name => "Unternehmensberatung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 177,  :name => "Versicherungen",  :country => "de"
print "."
Category.create!  :apphera_id  => 179,  :name => "Anglerbedarf ",  :country => "de"
print "."
Category.create!  :apphera_id  => 180,  :name => "Ballonfahrten ",  :country => "de"
print "."
Category.create!  :apphera_id  => 181,  :name => "Billard ",  :country => "de"
print "."
Category.create!  :apphera_id  => 182,  :name => "Boote",  :country => "de"
print "."
Category.create!  :apphera_id  => 183,  :name => "Bowlingbahnen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 184,  :name => "Camping",  :country => "de"
print "."
Category.create!  :apphera_id  => 185,  :name => "Fahrräder",  :country => "de"
print "."
Category.create!  :apphera_id  => 187,  :name => "Golf ",  :country => "de"
print "."
Category.create!  :apphera_id  => 188,  :name => "Hobby",  :country => "de"
print "."
Category.create!  :apphera_id  => 189,  :name => "Inlineskating ",  :country => "de"
print "."
Category.create!  :apphera_id  => 190,  :name => "Jagdbedarf ",  :country => "de"
print "."
Category.create!  :apphera_id  => 191,  :name => "Reiten ",  :country => "de"
print "."
Category.create!  :apphera_id  => 192,  :name => "Schwimmbäder ",  :country => "de"
print "."
Category.create!  :apphera_id  => 193,  :name => "Spielplätze ",  :country => "de"
print "."
Category.create!  :apphera_id  => 194,  :name => "Sportanlagen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 195,  :name => "Sportbedarf ",  :country => "de"
print "."
Category.create!  :apphera_id  => 196,  :name => "Tanzen",  :country => "de"
print "."
Category.create!  :apphera_id  => 197,  :name => "Tauchsport ",  :country => "de"
print "."
Category.create!  :apphera_id  => 198,  :name => "Tennis ",  :country => "de"
print "."
Category.create!  :apphera_id  => 199,  :name => "Vereine ",  :country => "de"
print "."
Category.create!  :apphera_id  => 200,  :name => "Wassersport ",  :country => "de"
print "."
Category.create!  :apphera_id  => 201,  :name => "Wettbüros ",  :country => "de"
print "."
Category.create!  :apphera_id  => 203,  :name => "Kunst",  :country => "de"
print "."
Category.create!  :apphera_id  => 204,  :name => "Erotik ",  :country => "de"
print "."
Category.create!  :apphera_id  => 205,  :name => "Film",  :country => "de"
print "."
Category.create!  :apphera_id  => 207,  :name => "Kultur ",  :country => "de"
print "."
Category.create!  :apphera_id  => 208,  :name => "Kunstgewerbe ",  :country => "de"
print "."
Category.create!  :apphera_id  => 209,  :name => "Model- und Castingagenturen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 210,  :name => "Museen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 211,  :name => "Musik",  :country => "de"
print "."
Category.create!  :apphera_id  => 212,  :name => "Nachtclubs ",  :country => "de"
print "."
Category.create!  :apphera_id  => 213,  :name => "Radio- und Fernsehsender ",  :country => "de"
print "."
Category.create!  :apphera_id  => 214,  :name => "Schauplätze",  :country => "de"
print "."
Category.create!  :apphera_id  => 215,  :name => "Theater ",  :country => "de"
print "."
Category.create!  :apphera_id  => 216,  :name => "Ticketverkauf ",  :country => "de"
print "."
Category.create!  :apphera_id  => 217,  :name => "Veranstaltungsservice ",  :country => "de"
print "."
Category.create!  :apphera_id  => 218,  :name => "Autogenes Training ",  :country => "de"
print "."
Category.create!  :apphera_id  => 219,  :name => "Drogeriewaren ",  :country => "de"
print "."
Category.create!  :apphera_id  => 221,  :name => "Hautpflege ",  :country => "de"
print "."
Category.create!  :apphera_id  => 222,  :name => "Kosmetikstudios & Friseursalons",  :country => "de"
print "."
Category.create!  :apphera_id  => 224,  :name => "Nagelpflege",  :country => "de"
print "."
Category.create!  :apphera_id  => 226,  :name => "Piercing & Tatoo",  :country => "de"
print "."
Category.create!  :apphera_id  => 227,  :name => "Saunabäder ",  :country => "de"
print "."
Category.create!  :apphera_id  => 228,  :name => "Sonnenstudios ",  :country => "de"
print "."
Category.create!  :apphera_id  => 229,  :name => "Yoga ",  :country => "de"
print "."
Category.create!  :apphera_id  => 230,  :name => "Antennen- und Satellitenbau",  :country => "de"
print "."
Category.create!  :apphera_id  => 231,  :name => "Bad Sanitär",  :country => "de"
print "."
Category.create!  :apphera_id  => 232,  :name => "Bau",  :country => "de"
print "."
Category.create!  :apphera_id  => 233,  :name => "Baumpflege ",  :country => "de"
print "."
Category.create!  :apphera_id  => 234,  :name => "Baumschule ",  :country => "de"
print "."
Category.create!  :apphera_id  => 235,  :name => "Baumärkte ",  :country => "de"
print "."
Category.create!  :apphera_id  => 236,  :name => "Brennstoffe ",  :country => "de"
print "."
Category.create!  :apphera_id  => 237,  :name => "Garagen",  :country => "de"
print "."
Category.create!  :apphera_id  => 238,  :name => "Gartenbau ",  :country => "de"
print "."
Category.create!  :apphera_id  => 239,  :name => "Gartencenter ",  :country => "de"
print "."
Category.create!  :apphera_id  => 242,  :name => "Hausdienstleistungen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 244,  :name => "Haussicherheit",  :country => "de"
print "."
Category.create!  :apphera_id  => 245,  :name => "Haustechnik ",  :country => "de"
print "."
Category.create!  :apphera_id  => 246,  :name => "Inneneinrichtung",  :country => "de"
print "."
Category.create!  :apphera_id  => 247,  :name => "Klimatechnik ",  :country => "de"
print "."
Category.create!  :apphera_id  => 248,  :name => "Lagerung & Beseitigung",  :country => "de"
print "."
Category.create!  :apphera_id  => 249,  :name => "Naturwaren ",  :country => "de"
print "."
Category.create!  :apphera_id  => 250,  :name => "Reinigung",  :country => "de"
print "."
Category.create!  :apphera_id  => 251,  :name => "Schleifereien ",  :country => "de"
print "."
Category.create!  :apphera_id  => 252,  :name => "Steinmetzbetriebe ",  :country => "de"
print "."
Category.create!  :apphera_id  => 253,  :name => "Terrasse & Balkon",  :country => "de"
print "."
Category.create!  :apphera_id  => 254,  :name => "Tore & Zäune",  :country => "de"
print "."
Category.create!  :apphera_id  => 255,  :name => "Treppen und Aufzüge",  :country => "de"
print "."
Category.create!  :apphera_id  => 256,  :name => "Versorgung",  :country => "de"
print "."
Category.create!  :apphera_id  => 257,  :name => "Werkzeuge ",  :country => "de"
print "."
Category.create!  :apphera_id  => 258,  :name => "Ferienhäuser ",  :country => "de"
print "."
Category.create!  :apphera_id  => 259,  :name => "Gästehäuser ",  :country => "de"
print "."
Category.create!  :apphera_id  => 260,  :name => "Hotels ",  :country => "de"
print "."
Category.create!  :apphera_id  => 261,  :name => "Jugendherbergen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 263,  :name => "Pensionen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 265,  :name => "Reiseveranstalter ",  :country => "de"
print "."
Category.create!  :apphera_id  => 266,  :name => "Busbetriebe ",  :country => "de"
print "."
Category.create!  :apphera_id  => 267,  :name => "Flughafen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 268,  :name => "Kurierdienste ",  :country => "de"
print "."
Category.create!  :apphera_id  => 269,  :name => "Logistik ",  :country => "de"
print "."
Category.create!  :apphera_id  => 270,  :name => "Mitfahrzentrale ",  :country => "de"
print "."
Category.create!  :apphera_id  => 271,  :name => "Schifffahrt ",  :country => "de"
print "."
Category.create!  :apphera_id  => 272,  :name => "Schwertransporte ",  :country => "de"
print "."
Category.create!  :apphera_id  => 273,  :name => "Speditionsgewerbe",  :country => "de"
print "."
Category.create!  :apphera_id  => 274,  :name => "Taxi- und Mietwagenverkehr ",  :country => "de"
print "."
Category.create!  :apphera_id  => 275,  :name => "Verkehrsbetriebe ",  :country => "de"
print "."
Category.create!  :apphera_id  => 276,  :name => "Verkehrstechnik ",  :country => "de"
print "."
Category.create!  :apphera_id  => 277,  :name => "Copyshop ",  :country => "de"
print "."
Category.create!  :apphera_id  => 278,  :name => "Drucken und Laminieren",  :country => "de"
print "."
Category.create!  :apphera_id  => 279,  :name => "Foto ",  :country => "de"
print "."
Category.create!  :apphera_id  => 280,  :name => "Grafikdesign ",  :country => "de"
print "."
Category.create!  :apphera_id  => 281,  :name => "Kommunikation",  :country => "de"
print "."
Category.create!  :apphera_id  => 282,  :name => "Lichtwerbung, Schilder und Stempel",  :country => "de"
print "."
Category.create!  :apphera_id  => 283,  :name => "Marktforschung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 284,  :name => "Medien- und Werbetechnik ",  :country => "de"
print "."
Category.create!  :apphera_id  => 285,  :name => "Verlagswesen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 286,  :name => "Werbeartikel ",  :country => "de"
print "."
Category.create!  :apphera_id  => 287,  :name => "Werbung, Promotion und Marketing ",  :country => "de"
print "."
Category.create!  :apphera_id  => 288,  :name => "Zeitungen und Zeitschriften",  :country => "de"
print "."
Category.create!  :apphera_id  => 289,  :name => "Aquaristik ",  :country => "de"
print "."
Category.create!  :apphera_id  => 290,  :name => "Facharzt für Tiermedizin ",  :country => "de"
print "."
Category.create!  :apphera_id  => 291,  :name => "Haustierpflege ",  :country => "de"
print "."
Category.create!  :apphera_id  => 292,  :name => "Imkereien ",  :country => "de"
print "."
Category.create!  :apphera_id  => 293,  :name => "Tierfriedhof ",  :country => "de"
print "."
Category.create!  :apphera_id  => 294,  :name => "Tierheim ",  :country => "de"
print "."
Category.create!  :apphera_id  => 295,  :name => "Tierpensionen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 296,  :name => "Tierschulen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 297,  :name => "Tierzucht ",  :country => "de"
print "."
Category.create!  :apphera_id  => 299,  :name => "Allgemeiner Einzelhandel ",  :country => "de"
print "."
Category.create!  :apphera_id  => 301,  :name => "Automaten ",  :country => "de"
print "."
Category.create!  :apphera_id  => 302,  :name => "Babyausstattung ",  :country => "de"
print "."
Category.create!  :apphera_id  => 303,  :name => "Blumen ",  :country => "de"
print "."
Category.create!  :apphera_id  => 304,  :name => "Bücher",  :country => "de"
print "."
Category.create!  :apphera_id  => 305,  :name => "Eisenwaren ",  :country => "de"
print "."
Category.create!  :apphera_id  => 306,  :name => "Elektronik",  :country => "de"
print "."
Category.create!  :apphera_id  => 307,  :name => "Geschenkartikel",  :country => "de"
print "."
Category.create!  :apphera_id  => 308,  :name => "Hobby und Freizeit",  :country => "de"
print "."
Category.create!  :apphera_id  => 309,  :name => "Hochzeit und Party",  :country => "de"
print "."
Category.create!  :apphera_id  => 310,  :name => "Kaufhäuser",  :country => "de"
print "."
Category.create!  :apphera_id  => 311,  :name => "Kioske ",  :country => "de"
print "."
Category.create!  :apphera_id  => 312,  :name => "Kleidung und Mode",  :country => "de"
print "."
Category.create!  :apphera_id  => 314,  :name => "Lederwaren ",  :country => "de"
print "."
Category.create!  :apphera_id  => 315,  :name => "Schmuck",  :country => "de"
print "."
Category.create!  :apphera_id  => 316,  :name => "Schuhe ",  :country => "de"
print "."
Category.create!  :apphera_id  => 317,  :name => "Schulbedarf ",  :country => "de"
print "."
Category.create!  :apphera_id  => 318,  :name => "Spielwaren ",  :country => "de"
print "."
Category.create!  :apphera_id  => 319,  :name => "Tabakwaren ",  :country => "de"
print "."
Category.create!  :apphera_id  => 320,  :name => "Textilien ",  :country => "de"
print "."
Category.create!  :apphera_id  => 322,  :name => "Uhren ",  :country => "de"
print "."
Category.create!  :apphera_id  => 324,  :name => "Zoohandlungen ",  :country => "de"
print "."

puts "Done writing Category"

ContentProvider.create!  :id => 1,  :name => "Yahoo",  :description => "Yahoo Local",  :url => "local.yahoo.com"
print "."
ContentProvider.create!  :id => 2,  :name => "Google",  :description => "Google Search ",  :url => "www.google.com"
print "."
ContentProvider.create!  :id => 3,  :name => "Urbanspoon",  :description => "Urbanspoon ",  :url => "www.urbanspoon.com"
print "."
ContentProvider.create!  :id => 4,  :name => "Yellowpages",  :description => "Yellowpages",  :url => "www.yellowpages.com"
print "."
ContentProvider.create!  :id => 5,  :name => "Yelp",  :description => "Yelp",  :url => "www.yelp.com"
print "."
ContentProvider.create!  :id => 6,  :name => "Bing",  :description => "Bing",  :url => "www.bing.com"
print "."
ContentProvider.create!  :id => 7,  :name => "Tripadvisor",  :description => "Tripadvisor",  :url => "www.tripadvisor.de"
print "."
ContentProvider.create!  :id => 8,  :name => "Google Germany",  :description => "The German Google Site",  :url => "www.google.de"
print "."
ContentProvider.create!  :id => 9,  :name => "Bing Germany",  :description => "Microsofts Bing Search Engine in Germany",  :url => "www.bing.de"
print "."
ContentProvider.create!  :id => 10,  :name => "Qype Germany",  :description => "Qype directory site",  :url => "www.qype.com"
print "."
ContentProvider.create!  :id => 11,  :name => "Facebook",  :description => "Facebook site",  :url => "www.facebook.com"
print "."
ContentProvider.create!  :id => 12,  :name => "KennstDuEinen.de",  :description => "Kennstdueinen Review Germany",  :url => "www.kennstdueinen.de"
print "."
ContentProvider.create!  :id => 13,  :name => "Pointoo",  :description => "German Pointoo Site",  :url => "www.pointoo.de"
print "."
ContentProvider.create!  :id => 14,  :name => "golocal",  :description => "golocal",  :url => "www.golocal.de"
print "."
ContentProvider.create!  :id => 15,  :name => "hotels",  :description => "Hotels.com",  :url => "www.hotels.com"
print "."
ContentProvider.create!  :id => 16,  :name => "meinestadt",  :description => "meinestadt.de",  :url => "www.meinestadt.de"
print "."
ContentProvider.create!  :id => 17,  :name => "restaurantkritik",  :description => "Restaurant Kritik Site",  :url => "www.restaurant-kritik.de"
print "."
ContentProvider.create!  :id => 18,  :name => "wowarstdu",  :description => "Wo warst Du",  :url => "www.wowarstdu.de"
print "."

puts "Done writing content providers"

CountryCodes.create!  :id => 1,  :code => "AD",  :name => "Andorra
"
print "."
CountryCodes.create!  :id => 2,  :code => "AE",  :name => "United Arab Emirates
"
print "."
CountryCodes.create!  :id => 3,  :code => "AF",  :name => "Afghanistan
"
print "."
CountryCodes.create!  :id => 4,  :code => "AG",  :name => "Antigua and Barbuda
"
print "."
CountryCodes.create!  :id => 5,  :code => "AI",  :name => "Anguilla
"
print "."
CountryCodes.create!  :id => 6,  :code => "AL",  :name => "Albania
"
print "."
CountryCodes.create!  :id => 7,  :code => "AM",  :name => "Armenia
"
print "."
CountryCodes.create!  :id => 8,  :code => "AN",  :name => "Netherlands Antilles
"
print "."
CountryCodes.create!  :id => 9,  :code => "AO",  :name => "Angola
"
print "."
CountryCodes.create!  :id => 10,  :code => "AQ",  :name => "Antarctica
"
print "."
CountryCodes.create!  :id => 11,  :code => "AR",  :name => "Argentina
"
print "."
CountryCodes.create!  :id => 12,  :code => "AS",  :name => "American Samoa
"
print "."
CountryCodes.create!  :id => 13,  :code => "AT",  :name => "Austria
"
print "."
CountryCodes.create!  :id => 14,  :code => "AU",  :name => "Australia
"
print "."
CountryCodes.create!  :id => 15,  :code => "AW",  :name => "Aruba
"
print "."
CountryCodes.create!  :id => 16,  :code => "AX",  :name => "Aland Islands
"
print "."
CountryCodes.create!  :id => 17,  :code => "AZ",  :name => "Azerbaijan
"
print "."
CountryCodes.create!  :id => 18,  :code => "BA",  :name => "Bosnia and Herzegovina
"
print "."
CountryCodes.create!  :id => 19,  :code => "BB",  :name => "Barbados
"
print "."
CountryCodes.create!  :id => 20,  :code => "BD",  :name => "Bangladesh
"
print "."
CountryCodes.create!  :id => 21,  :code => "BE",  :name => "Belgium
"
print "."
CountryCodes.create!  :id => 22,  :code => "BF",  :name => "Burkina Faso
"
print "."
CountryCodes.create!  :id => 23,  :code => "BG",  :name => "Bulgaria
"
print "."
CountryCodes.create!  :id => 24,  :code => "BH",  :name => "Bahrain
"
print "."
CountryCodes.create!  :id => 25,  :code => "BI",  :name => "Burundi
"
print "."
CountryCodes.create!  :id => 26,  :code => "BJ",  :name => "Benin
"
print "."
CountryCodes.create!  :id => 27,  :code => "BM",  :name => "Bermuda
"
print "."
CountryCodes.create!  :id => 28,  :code => "BN",  :name => "Brunei Darussalam
"
print "."
CountryCodes.create!  :id => 29,  :code => "BO",  :name => "Bolivia
"
print "."
CountryCodes.create!  :id => 30,  :code => "BR",  :name => "Brazil
"
print "."
CountryCodes.create!  :id => 31,  :code => "BS",  :name => "Bahamas
"
print "."
CountryCodes.create!  :id => 32,  :code => "BT",  :name => "Bhutan
"
print "."
CountryCodes.create!  :id => 33,  :code => "BV",  :name => "Bouvet Island
"
print "."
CountryCodes.create!  :id => 34,  :code => "BW",  :name => "Botswana
"
print "."
CountryCodes.create!  :id => 35,  :code => "BY",  :name => "Belarus
"
print "."
CountryCodes.create!  :id => 36,  :code => "BZ",  :name => "Belize
"
print "."
CountryCodes.create!  :id => 37,  :code => "CA",  :name => "Canada
"
print "."
CountryCodes.create!  :id => 38,  :code => "CC",  :name => "Cocos (Keeling) Islands
"
print "."
CountryCodes.create!  :id => 39,  :code => "CD",  :name => "Democratic Republic of the Congo
"
print "."
CountryCodes.create!  :id => 40,  :code => "CF",  :name => "Central African Republic
"
print "."
CountryCodes.create!  :id => 41,  :code => "CG",  :name => "Congo
"
print "."
CountryCodes.create!  :id => 42,  :code => "CH",  :name => "Switzerland
"
print "."
CountryCodes.create!  :id => 43,  :code => "CI",  :name => "Cote D'Ivoire (Ivory Coast)
"
print "."
CountryCodes.create!  :id => 44,  :code => "CK",  :name => "Cook Islands
"
print "."
CountryCodes.create!  :id => 45,  :code => "CL",  :name => "Chile
"
print "."
CountryCodes.create!  :id => 46,  :code => "CM",  :name => "Cameroon
"
print "."
CountryCodes.create!  :id => 47,  :code => "CN",  :name => "China
"
print "."
CountryCodes.create!  :id => 48,  :code => "CO",  :name => "Colombia
"
print "."
CountryCodes.create!  :id => 49,  :code => "CR",  :name => "Costa Rica
"
print "."
CountryCodes.create!  :id => 50,  :code => "CS",  :name => "Serbia and Montenegro
"
print "."
CountryCodes.create!  :id => 51,  :code => "CU",  :name => "Cuba
"
print "."
CountryCodes.create!  :id => 52,  :code => "CV",  :name => "Cape Verde
"
print "."
CountryCodes.create!  :id => 53,  :code => "CX",  :name => "Christmas Island
"
print "."
CountryCodes.create!  :id => 54,  :code => "CY",  :name => "Cyprus
"
print "."
CountryCodes.create!  :id => 55,  :code => "CZ",  :name => "Czech Republic
"
print "."
CountryCodes.create!  :id => 56,  :code => "DE",  :name => "Germany
"
print "."
CountryCodes.create!  :id => 57,  :code => "DJ",  :name => "Djibouti
"
print "."
CountryCodes.create!  :id => 58,  :code => "DK",  :name => "Denmark
"
print "."
CountryCodes.create!  :id => 59,  :code => "DM",  :name => "Dominica
"
print "."
CountryCodes.create!  :id => 60,  :code => "DO",  :name => "Dominican Republic
"
print "."
CountryCodes.create!  :id => 61,  :code => "DZ",  :name => "Algeria
"
print "."
CountryCodes.create!  :id => 62,  :code => "EC",  :name => "Ecuador
"
print "."
CountryCodes.create!  :id => 63,  :code => "EE",  :name => "Estonia
"
print "."
CountryCodes.create!  :id => 64,  :code => "EG",  :name => "Egypt
"
print "."
CountryCodes.create!  :id => 65,  :code => "EH",  :name => "Western Sahara
"
print "."
CountryCodes.create!  :id => 66,  :code => "ER",  :name => "Eritrea
"
print "."
CountryCodes.create!  :id => 67,  :code => "ES",  :name => "Spain
"
print "."
CountryCodes.create!  :id => 68,  :code => "ET",  :name => "Ethiopia
"
print "."
CountryCodes.create!  :id => 69,  :code => "FI",  :name => "Finland
"
print "."
CountryCodes.create!  :id => 70,  :code => "FJ",  :name => "Fiji
"
print "."
CountryCodes.create!  :id => 71,  :code => "FK",  :name => "Falkland Islands (Malvinas)
"
print "."
CountryCodes.create!  :id => 72,  :code => "FM",  :name => "Federated States of Micronesia
"
print "."
CountryCodes.create!  :id => 73,  :code => "FO",  :name => "Faroe Islands
"
print "."
CountryCodes.create!  :id => 74,  :code => "FR",  :name => "France
"
print "."
CountryCodes.create!  :id => 75,  :code => "FX",  :name => "France, Metropolitan
"
print "."
CountryCodes.create!  :id => 76,  :code => "GA",  :name => "Gabon
"
print "."
CountryCodes.create!  :id => 77,  :code => "GB",  :name => "Great Britain (UK)
"
print "."
CountryCodes.create!  :id => 78,  :code => "GD",  :name => "Grenada
"
print "."
CountryCodes.create!  :id => 79,  :code => "GE",  :name => "Georgia
"
print "."
CountryCodes.create!  :id => 80,  :code => "GF",  :name => "French Guiana
"
print "."
CountryCodes.create!  :id => 81,  :code => "GH",  :name => "Ghana
"
print "."
CountryCodes.create!  :id => 82,  :code => "GI",  :name => "Gibraltar
"
print "."
CountryCodes.create!  :id => 83,  :code => "GL",  :name => "Greenland
"
print "."
CountryCodes.create!  :id => 84,  :code => "GM",  :name => "Gambia
"
print "."
CountryCodes.create!  :id => 85,  :code => "GN",  :name => "Guinea
"
print "."
CountryCodes.create!  :id => 86,  :code => "GP",  :name => "Guadeloupe
"
print "."
CountryCodes.create!  :id => 87,  :code => "GQ",  :name => "Equatorial Guinea
"
print "."
CountryCodes.create!  :id => 88,  :code => "GR",  :name => "Greece
"
print "."
CountryCodes.create!  :id => 89,  :code => "GS",  :name => "S. Georgia and S. Sandwich Islands
"
print "."
CountryCodes.create!  :id => 90,  :code => "GT",  :name => "Guatemala
"
print "."
CountryCodes.create!  :id => 91,  :code => "GU",  :name => "Guam
"
print "."
CountryCodes.create!  :id => 92,  :code => "GW",  :name => "Guinea-Bissau
"
print "."
CountryCodes.create!  :id => 93,  :code => "GY",  :name => "Guyana
"
print "."
CountryCodes.create!  :id => 94,  :code => "HK",  :name => "Hong Kong
"
print "."
CountryCodes.create!  :id => 95,  :code => "HM",  :name => "Heard Island and McDonald Islands
"
print "."
CountryCodes.create!  :id => 96,  :code => "HN",  :name => "Honduras
"
print "."
CountryCodes.create!  :id => 97,  :code => "HR",  :name => "Croatia (Hrvatska)
"
print "."
CountryCodes.create!  :id => 98,  :code => "HT",  :name => "Haiti
"
print "."
CountryCodes.create!  :id => 99,  :code => "HU",  :name => "Hungary
"
print "."
CountryCodes.create!  :id => 100,  :code => "ID",  :name => "Indonesia
"
print "."
CountryCodes.create!  :id => 101,  :code => "IE",  :name => "Ireland
"
print "."
CountryCodes.create!  :id => 102,  :code => "IL",  :name => "Israel
"
print "."
CountryCodes.create!  :id => 103,  :code => "IN",  :name => "India
"
print "."
CountryCodes.create!  :id => 104,  :code => "IO",  :name => "British Indian Ocean Territory
"
print "."
CountryCodes.create!  :id => 105,  :code => "IQ",  :name => "Iraq
"
print "."
CountryCodes.create!  :id => 106,  :code => "IR",  :name => "Iran
"
print "."
CountryCodes.create!  :id => 107,  :code => "IS",  :name => "Iceland
"
print "."
CountryCodes.create!  :id => 108,  :code => "IT",  :name => "Italy
"
print "."
CountryCodes.create!  :id => 109,  :code => "JM",  :name => "Jamaica
"
print "."
CountryCodes.create!  :id => 110,  :code => "JO",  :name => "Jordan
"
print "."
CountryCodes.create!  :id => 111,  :code => "JP",  :name => "Japan
"
print "."
CountryCodes.create!  :id => 112,  :code => "KE",  :name => "Kenya
"
print "."
CountryCodes.create!  :id => 113,  :code => "KG",  :name => "Kyrgyzstan
"
print "."
CountryCodes.create!  :id => 114,  :code => "KH",  :name => "Cambodia
"
print "."
CountryCodes.create!  :id => 115,  :code => "KI",  :name => "Kiribati
"
print "."
CountryCodes.create!  :id => 116,  :code => "KM",  :name => "Comoros
"
print "."
CountryCodes.create!  :id => 117,  :code => "KN",  :name => "Saint Kitts and Nevis
"
print "."
CountryCodes.create!  :id => 118,  :code => "KP",  :name => "Korea (North)
"
print "."
CountryCodes.create!  :id => 119,  :code => "KR",  :name => "Korea (South)
"
print "."
CountryCodes.create!  :id => 120,  :code => "KW",  :name => "Kuwait
"
print "."
CountryCodes.create!  :id => 121,  :code => "KY",  :name => "Cayman Islands
"
print "."
CountryCodes.create!  :id => 122,  :code => "KZ",  :name => "Kazakhstan
"
print "."
CountryCodes.create!  :id => 123,  :code => "LA",  :name => "Laos
"
print "."
CountryCodes.create!  :id => 124,  :code => "LB",  :name => "Lebanon
"
print "."
CountryCodes.create!  :id => 125,  :code => "LC",  :name => "Saint Lucia
"
print "."
CountryCodes.create!  :id => 126,  :code => "LI",  :name => "Liechtenstein
"
print "."
CountryCodes.create!  :id => 127,  :code => "LK",  :name => "Sri Lanka
"
print "."
CountryCodes.create!  :id => 128,  :code => "LR",  :name => "Liberia
"
print "."
CountryCodes.create!  :id => 129,  :code => "LS",  :name => "Lesotho
"
print "."
CountryCodes.create!  :id => 130,  :code => "LT",  :name => "Lithuania
"
print "."
CountryCodes.create!  :id => 131,  :code => "LU",  :name => "Luxembourg
"
print "."
CountryCodes.create!  :id => 132,  :code => "LV",  :name => "Latvia
"
print "."
CountryCodes.create!  :id => 133,  :code => "LY",  :name => "Libya
"
print "."
CountryCodes.create!  :id => 134,  :code => "MA",  :name => "Morocco
"
print "."
CountryCodes.create!  :id => 135,  :code => "MC",  :name => "Monaco
"
print "."
CountryCodes.create!  :id => 136,  :code => "MD",  :name => "Moldova
"
print "."
CountryCodes.create!  :id => 137,  :code => "MG",  :name => "Madagascar
"
print "."
CountryCodes.create!  :id => 138,  :code => "MH",  :name => "Marshall Islands
"
print "."
CountryCodes.create!  :id => 139,  :code => "MK",  :name => "Macedonia
"
print "."
CountryCodes.create!  :id => 140,  :code => "ML",  :name => "Mali
"
print "."
CountryCodes.create!  :id => 141,  :code => "MM",  :name => "Myanmar
"
print "."
CountryCodes.create!  :id => 142,  :code => "MN",  :name => "Mongolia
"
print "."
CountryCodes.create!  :id => 143,  :code => "MO",  :name => "Macao
"
print "."
CountryCodes.create!  :id => 144,  :code => "MP",  :name => "Northern Mariana Islands
"
print "."
CountryCodes.create!  :id => 145,  :code => "MQ",  :name => "Martinique
"
print "."
CountryCodes.create!  :id => 146,  :code => "MR",  :name => "Mauritania
"
print "."
CountryCodes.create!  :id => 147,  :code => "MS",  :name => "Montserrat
"
print "."
CountryCodes.create!  :id => 148,  :code => "MT",  :name => "Malta
"
print "."
CountryCodes.create!  :id => 149,  :code => "MU",  :name => "Mauritius
"
print "."
CountryCodes.create!  :id => 150,  :code => "MV",  :name => "Maldives
"
print "."
CountryCodes.create!  :id => 151,  :code => "MW",  :name => "Malawi
"
print "."
CountryCodes.create!  :id => 152,  :code => "MX",  :name => "Mexico
"
print "."
CountryCodes.create!  :id => 153,  :code => "MY",  :name => "Malaysia
"
print "."
CountryCodes.create!  :id => 154,  :code => "MZ",  :name => "Mozambique
"
print "."
CountryCodes.create!  :id => 155,  :code => "NA",  :name => "Namibia
"
print "."
CountryCodes.create!  :id => 156,  :code => "NC",  :name => "New Caledonia
"
print "."
CountryCodes.create!  :id => 157,  :code => "NE",  :name => "Niger
"
print "."
CountryCodes.create!  :id => 158,  :code => "NF",  :name => "Norfolk Island
"
print "."
CountryCodes.create!  :id => 159,  :code => "NG",  :name => "Nigeria
"
print "."
CountryCodes.create!  :id => 160,  :code => "NI",  :name => "Nicaragua
"
print "."
CountryCodes.create!  :id => 161,  :code => "NL",  :name => "Netherlands
"
print "."
CountryCodes.create!  :id => 162,  :code => "NO",  :name => "Norway
"
print "."
CountryCodes.create!  :id => 163,  :code => "NP",  :name => "Nepal
"
print "."
CountryCodes.create!  :id => 164,  :code => "NR",  :name => "Nauru
"
print "."
CountryCodes.create!  :id => 165,  :code => "NU",  :name => "Niue
"
print "."
CountryCodes.create!  :id => 166,  :code => "NZ",  :name => "New Zealand (Aotearoa)
"
print "."
CountryCodes.create!  :id => 167,  :code => "OM",  :name => "Oman
"
print "."
CountryCodes.create!  :id => 168,  :code => "PA",  :name => "Panama
"
print "."
CountryCodes.create!  :id => 169,  :code => "PE",  :name => "Peru
"
print "."
CountryCodes.create!  :id => 170,  :code => "PF",  :name => "French Polynesia
"
print "."
CountryCodes.create!  :id => 171,  :code => "PG",  :name => "Papua New Guinea
"
print "."
CountryCodes.create!  :id => 172,  :code => "PH",  :name => "Philippines
"
print "."
CountryCodes.create!  :id => 173,  :code => "PK",  :name => "Pakistan
"
print "."
CountryCodes.create!  :id => 174,  :code => "PL",  :name => "Poland
"
print "."
CountryCodes.create!  :id => 175,  :code => "PM",  :name => "Saint Pierre and Miquelon
"
print "."
CountryCodes.create!  :id => 176,  :code => "PN",  :name => "Pitcairn
"
print "."
CountryCodes.create!  :id => 177,  :code => "PR",  :name => "Puerto Rico
"
print "."
CountryCodes.create!  :id => 178,  :code => "PS",  :name => "Palestinian Territory
"
print "."
CountryCodes.create!  :id => 179,  :code => "PT",  :name => "Portugal
"
print "."
CountryCodes.create!  :id => 180,  :code => "PW",  :name => "Palau
"
print "."
CountryCodes.create!  :id => 181,  :code => "PY",  :name => "Paraguay
"
print "."
CountryCodes.create!  :id => 182,  :code => "QA",  :name => "Qatar
"
print "."
CountryCodes.create!  :id => 183,  :code => "RE",  :name => "Reunion
"
print "."
CountryCodes.create!  :id => 184,  :code => "RO",  :name => "Romania
"
print "."
CountryCodes.create!  :id => 185,  :code => "RU",  :name => "Russian Federation
"
print "."
CountryCodes.create!  :id => 186,  :code => "RW",  :name => "Rwanda
"
print "."
CountryCodes.create!  :id => 187,  :code => "SA",  :name => "Saudi Arabia
"
print "."
CountryCodes.create!  :id => 188,  :code => "SB",  :name => "Solomon Islands
"
print "."
CountryCodes.create!  :id => 189,  :code => "SC",  :name => "Seychelles
"
print "."
CountryCodes.create!  :id => 190,  :code => "SD",  :name => "Sudan
"
print "."
CountryCodes.create!  :id => 191,  :code => "SE",  :name => "Sweden
"
print "."
CountryCodes.create!  :id => 192,  :code => "SG",  :name => "Singapore
"
print "."
CountryCodes.create!  :id => 193,  :code => "SH",  :name => "Saint Helena
"
print "."
CountryCodes.create!  :id => 194,  :code => "SI",  :name => "Slovenia
"
print "."
CountryCodes.create!  :id => 195,  :code => "SJ",  :name => "Svalbard and Jan Mayen
"
print "."
CountryCodes.create!  :id => 196,  :code => "SK",  :name => "Slovakia
"
print "."
CountryCodes.create!  :id => 197,  :code => "SL",  :name => "Sierra Leone
"
print "."
CountryCodes.create!  :id => 198,  :code => "SM",  :name => "San Marino
"
print "."
CountryCodes.create!  :id => 199,  :code => "SN",  :name => "Senegal
"
print "."
CountryCodes.create!  :id => 200,  :code => "SO",  :name => "Somalia
"
print "."
CountryCodes.create!  :id => 201,  :code => "SR",  :name => "Suriname
"
print "."
CountryCodes.create!  :id => 202,  :code => "ST",  :name => "Sao Tome and Principe
"
print "."
CountryCodes.create!  :id => 203,  :code => "SU",  :name => "USSR (former)
"
print "."
CountryCodes.create!  :id => 204,  :code => "SV",  :name => "El Salvador
"
print "."
CountryCodes.create!  :id => 205,  :code => "SY",  :name => "Syria
"
print "."
CountryCodes.create!  :id => 206,  :code => "SZ",  :name => "Swaziland
"
print "."
CountryCodes.create!  :id => 207,  :code => "TC",  :name => "Turks and Caicos Islands
"
print "."
CountryCodes.create!  :id => 208,  :code => "TD",  :name => "Chad
"
print "."
CountryCodes.create!  :id => 209,  :code => "TF",  :name => "French Southern Territories
"
print "."
CountryCodes.create!  :id => 210,  :code => "TG",  :name => "Togo
"
print "."
CountryCodes.create!  :id => 211,  :code => "TH",  :name => "Thailand
"
print "."
CountryCodes.create!  :id => 212,  :code => "TJ",  :name => "Tajikistan
"
print "."
CountryCodes.create!  :id => 213,  :code => "TK",  :name => "Tokelau
"
print "."
CountryCodes.create!  :id => 214,  :code => "TL",  :name => "Timor-Leste
"
print "."
CountryCodes.create!  :id => 215,  :code => "TM",  :name => "Turkmenistan
"
print "."
CountryCodes.create!  :id => 216,  :code => "TN",  :name => "Tunisia
"
print "."
CountryCodes.create!  :id => 217,  :code => "TO",  :name => "Tonga
"
print "."
CountryCodes.create!  :id => 218,  :code => "TP",  :name => "East Timor
"
print "."
CountryCodes.create!  :id => 219,  :code => "TR",  :name => "Turkey
"
print "."
CountryCodes.create!  :id => 220,  :code => "TT",  :name => "Trinidad and Tobago
"
print "."
CountryCodes.create!  :id => 221,  :code => "TV",  :name => "Tuvalu
"
print "."
CountryCodes.create!  :id => 222,  :code => "TW",  :name => "Taiwan
"
print "."
CountryCodes.create!  :id => 223,  :code => "TZ",  :name => "Tanzania
"
print "."
CountryCodes.create!  :id => 224,  :code => "UA",  :name => "Ukraine
"
print "."
CountryCodes.create!  :id => 225,  :code => "UG",  :name => "Uganda
"
print "."
CountryCodes.create!  :id => 226,  :code => "UK",  :name => "United Kingdom
"
print "."
CountryCodes.create!  :id => 227,  :code => "UM",  :name => "United States Minor Outlying Islands
"
print "."
CountryCodes.create!  :id => 228,  :code => "US",  :name => "United States
"
print "."
CountryCodes.create!  :id => 229,  :code => "UY",  :name => "Uruguay
"
print "."
CountryCodes.create!  :id => 230,  :code => "UZ",  :name => "Uzbekistan
"
print "."
CountryCodes.create!  :id => 231,  :code => "VA",  :name => "Vatican City State (Holy See)
"
print "."
CountryCodes.create!  :id => 232,  :code => "VC",  :name => "Saint Vincent and the Grenadines
"
print "."
CountryCodes.create!  :id => 233,  :code => "VE",  :name => "Venezuela
"
print "."
CountryCodes.create!  :id => 234,  :code => "VG",  :name => "Virgin Islands (British)
"
print "."
CountryCodes.create!  :id => 235,  :code => "VI",  :name => "Virgin Islands (U.S.)
"
print "."
CountryCodes.create!  :id => 236,  :code => "VN",  :name => "Viet Nam
"
print "."
CountryCodes.create!  :id => 237,  :code => "VU",  :name => "Vanuatu
"
print "."
CountryCodes.create!  :id => 238,  :code => "WF",  :name => "Wallis and Futuna
"
print "."
CountryCodes.create!  :id => 239,  :code => "WS",  :name => "Samoa
"
print "."
CountryCodes.create!  :id => 240,  :code => "YE",  :name => "Yemen
"
print "."
CountryCodes.create!  :id => 241,  :code => "YT",  :name => "Mayotte
"
print "."
CountryCodes.create!  :id => 242,  :code => "YU",  :name => "Yugoslavia (former)
"
print "."
CountryCodes.create!  :id => 243,  :code => "ZA",  :name => "South Africa
"
print "."
CountryCodes.create!  :id => 244,  :code => "ZM",  :name => "Zambia
"
print "."
CountryCodes.create!  :id => 245,  :code => "ZR",  :name => "Zaire (former)
"
print "."
CountryCodes.create!  :id => 246,  :code => "ZW",  :name => "Zimbabwe
"
print "."
CountryCodes.create!  :id => 247,  :code => "BIZ",  :name => "Business
"
print "."
CountryCodes.create!  :id => 248,  :code => "COM",  :name => "Commercial
"
print "."
CountryCodes.create!  :id => 249,  :code => "EDU",  :name => "US Educational
"
print "."
CountryCodes.create!  :id => 250,  :code => "GOV",  :name => "US Government
"
print "."
CountryCodes.create!  :id => 251,  :code => "INT",  :name => "International
"
print "."
CountryCodes.create!  :id => 252,  :code => "MIL",  :name => "US Military
"
print "."
CountryCodes.create!  :id => 253,  :code => "NET",  :name => "Network
"
print "."
CountryCodes.create!  :id => 254,  :code => "ORG",  :name => "Nonprofit Organization
"
print "."
CountryCodes.create!  :id => 255,  :code => "PRO",  :name => "Professional Services
"
print "."
CountryCodes.create!  :id => 256,  :code => "AERO",  :name => "Aeronautic
"
print "."
CountryCodes.create!  :id => 257,  :code => "ARPA",  :name => "Arpanet Technical Infrastructure
"
print "."
CountryCodes.create!  :id => 258,  :code => "COOP",  :name => "Cooperative
"
print "."
CountryCodes.create!  :id => 259,  :code => "INFO",  :name => "Info Domain
"
print "."
CountryCodes.create!  :id => 260,  :code => "NAME",  :name => "Personal Name
"
print "."
CountryCodes.create!  :id => 261,  :code => "NATO",  :name => "North Atlantic Treaty Organization"
print "."

puts "Done writing country codes"

Sequence.create!  :id => 2,  :name => "New Customer Signup",  :description => "Initialize customer, find slugs, competitors, geo code, rankings"
print "."
Sequence.create!  :id => 3,  :name => "Daily crawl",  :description => "Daily monitoring jobs"
print "."
Sequence.create!  :id => 4,  :name => "Weekly crawl",  :description => "Weekly monitoring jobs"
print "."
Sequence.create!  :id => 5,  :name => "Calculate Totals",  :description => "Start business intelligence jobs"
print "."
Sequence.create!  :id => 6,  :name => "New",  :description => "Just Added"
print "."
Sequence.create!  :id => 7,  :name => "Ranking",  :description => "Get Google and Bing rankings"
print "."
Sequence.create!  :id => 8,  :name => "social",  :description => ""
print "."
Sequence.create!  :id => 9,  :name => "Alert",  :description => "Send alert mail"
print "."

puts "Done writing sequences"

SequenceItem.create!  :id => 2,  :name => "GetProxyList",  :description => "Loads new list of proxies."
print "."
SequenceItem.create!  :id => 3,  :name => "GoogleSlug",  :description => "Get's slugs for different content providers such as Urbanspoon, yahoo, zagat and others"
print "."
SequenceItem.create!  :id => 4,  :name => "CompetitorsGermany",  :description => "Get the German list of competitors for an organization"
print "."
SequenceItem.create!  :id => 5,  :name => "FacebookTwitter",  :description => "Trying to get Facebook and Twitter urls from homepage"
print "."
SequenceItem.create!  :id => 6,  :name => "ParseCompetitors",  :description => "Parse the new Comps"
print "."
SequenceItem.create!  :id => 7,  :name => "crawler.qype",  :description => "Get new Qype reviews"
print "."
SequenceItem.create!  :id => 8,  :name => "geo",  :description => "get lat and long from google"
print "."
SequenceItem.create!  :id => 9,  :name => "crawler.kennstdueinen",  :description => "German kennstdueinen.de site for reviews"
print "."
SequenceItem.create!  :id => 10,  :name => "crawler.tripadvisor",  :description => "Get reviews from tripadvisor"
print "."
SequenceItem.create!  :id => 11,  :name => "aggregate",  :description => "calculate totals"
print "."
SequenceItem.create!  :id => 12,  :name => "foursquare",  :description => "foursquare data like checkins etc."
print "."
SequenceItem.create!  :id => 15,  :name => "Ranks",  :description => "Get Google and Bing ranks"
print "."
SequenceItem.create!  :id => 16,  :name => "crawler.pointoo",  :description => "Pointoo reviews"
print "."
SequenceItem.create!  :id => 17,  :name => "crawler.yelp",  :description => "Yelp crawler in Germany"
print "."
SequenceItem.create!  :id => 18,  :name => "crawler.restaurantkritik",  :description => "Restaurant Kritik"
print "."
SequenceItem.create!  :id => 19,  :name => "crawler.meinestadt",  :description => "Meine Stadt Reviews"
print "."
SequenceItem.create!  :id => 20,  :name => "crawler.hotels",  :description => "Hotels.com Reviews"
print "."
SequenceItem.create!  :id => 21,  :name => "crawler.golocal",  :description => "Golocal"
print "."
SequenceItem.create!  :id => 22,  :name => "uptime_monitor",  :description => "website monitor"
print "."
SequenceItem.create!  :id => 23,  :name => "alert_mail",  :description => "send out alert mail"
print "."
puts "Done writing sequence items"
 
puts "completed"

